### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by vbauer** [Gperez88/MapperObject#7]
Could you please provide some additional documentation (in the README file) how to use this project?

**Comment by wilsoncampusano** [comment]
working on it

**Comment by wilsoncampusano** [comment]
you can review the docs now @vbauer

**Comment by wilsoncampusano** [comment]
@Gperez88 i think you should close this issue.

**Comment by vbauer** [comment]
Thank you!

**Comment by Gperez88** [comment]
close issue
